### ISSUE TITLE
create script for checking lambda logs

### ISSUE THREAD

**Issue by danmermel** [danmermel/photoalbumv2#16]

**Comment by danmermel** [comment]
aws logs describe-log-groups --query logGroups[*].logGroupName

aws logs describe-log-streams --log-group-name '/aws/lambda/resizerv2-stage' --query logStreams[*].logStreamName

aws logs get-log-events --log-group-name '/aws/lambda/MyFunction' --log-stream-name '2018/02/07/[$LATEST]140c61ffd59442b7b8405dc91d708fdc'

**Comment by glynnbird** [comment]
Don't bother:

```
aws logs tail /aws/lambda/feedfetch
```
