### ISSUE TITLE
Albums view

### ISSUE THREAD

**Issue by danmermel** [danmermel/photoalbumv2#3]
As a logged in user I want to see a list of my albums and I should be able to 
* click on any of them to view its contents
* Click on a link to Add a new album
* Delete any albums that are empty

**Comment by glynnbird** [comment]
- create a Lambda with a Lambda URL and output it to `frontend/config.json`
- call the Lambda from the front end passing the API_KEY from local storage
- the Lambda gets a list of top-level folders from S3 and returns them
