### ISSUE TITLE
Album content

### ISSUE THREAD

**Issue by danmermel** [danmermel/photoalbumv2#4]
As a user who has clicked on an album I want to:
* See how many photos the album contains
* See x number of thumbnails in the album
* Scroll through the contents of the album, progressively seeing more thumbnails
* Click on an individual photo to enlarge it
* Link to return to the album list view
* Link to upload photos to the album

**Comment by glynnbird** [comment]
See Vuetify's image grid example https://vuetifyjs.com/en/components/images/#grid

**Comment by danmermel** [comment]
* lambda that takes a album name and returns the first x items in the album with pre-signed urls to the thumbnails so that the frontend can display them
* Create page called /album/_id.vue which calls the above lambda and renders a list of thumbnails
* Each thumbnail is a link to /album/_id/item/_id
* We display up to x items (after we figure out how to use the marker to get more images)
* Find out how we do progressive loading of more images
