### ISSUE TITLE
Single photo view

### ISSUE THREAD

**Issue by danmermel** [danmermel/photoalbumv2#5]
As I user who has clicked on a thumbnail I want to:
* See the full size image
* See the clickable tags associated with the image
* See any exif data associated with the image
* Link to download image
* Link to share a URL to the image (with some expiration date)
* Link to delete the image

**Comment by glynnbird** [comment]
- create a lambda to return a presigned url for full size image, and a download link and the tag meta data for the image
- create links on album/_id for each thumbnail to link to /album/_id/item/_id
- create a new route at  /album/_id/item/_id to call the lambda and render the image and tags
- add button to provide download functionality
- hold off on deletion until the back end triggers are in place
